[theme]
primaryColor = "#2563eb"
backgroundColor = "#080e1a"
secondaryBackgroundColor = "#0f172a"
textColor = "#f8fafc"
font = "sans serif"

[server]
headless = true

[client]
toolbarMode = "minimal"
